apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-service
  labels:
    app: db-service
spec:
  imagePullSecrets:
    - name: regcred
  replicas: 1
  selector:
    matchLabels:
      app: db-service
  template:
    metadata:
      labels:
        app: db-service
    spec:
      containers:
        - name: db-service
          image: nhqb3197/db-service
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /db/health
              port: 8000
            livenessProbe:
              httpGet:
                path: /db/health
                port: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: db-service
  ports:
    - port: 8000
      targetPort: 8000