apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./user-service.yaml
  - ./store-service.yaml
  - ./db-service.yaml
  - ./admin-service.yaml

images:
  - name: nhqb/user-service
    newTag: v1.0.0
  - name: nhqb/store-service
    newTag: v1.0.0
  - name: nhqb/db-service
    newTag: v1.0.0
  - name: nhqb/admin-service
    newTag: v1.0.0