apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-service
  labels:
    app: store-service
spec:
  imagePullSecrets:
    - name: regcred
  replicas: 1
  selector:
    matchLabels:
      app: store-service
  template:
    metadata:
      labels:
        app: store-service
    spec:
      containers:
        - name: store-service
          image: nhqb3197/store-service:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /store/health
              port: 8000
            livenessProbe:
              httpGet:
                path: /store/health
                port: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: store-service
spec:
  selector:
    app: store-service
  ports:
    - port: 8000
      targetPort: 8000